require("dotenv").config({ path: require("path").join(__dirname, ".env") });
const express = require("express");
const cors = require("cors");
const dbConfig = require("./dbConfig");
const cloudinaryConfig = require("./config/cloudinaryConfig");
const route = require("./router");
const cookieParser = require("cookie-parser");
const errorHandler = require("./middleware/errorHandler");
const app = express();
app.use(cors());
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
dbConfig();
cloudinaryConfig();
app.use(errorHandler);
app.use(cookieParser());
const port = 8000;
app.use(route);
app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
